services:
  front:
    container_name: front
    build:
      context: ./front
    ports:
      - "80:3000"
  api:
    container_name: api
    build:
      context: ./api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/workchat
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:16.0-alpine
    container_name: db
    environment:
      POSTGRES_DB: workchat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin